#!/bin/sh

#	--apt-indices false \
#	--debootstrap-options "--variant=minbase" \
#	--firmware-chroot false \
#	--memtest none \

lb config noauto \
	--apt-recommends false \
	--bootappend-live "boot=live components hostname=tno-pki-m nopersistance username=mikpont" \
	--debian-installer-gui false \
	--iso-application "TNO Privatekey manager" \
	--iso-publisher "Serge Tensen" \
	"${@}"
