#!/bin/sh

#	--debootstrap-options "--variant=minbase" \ This command generates a Kernel Panic.


set -e

lb config noauto \
	--apt-indices false \
	--apt-recommends false \
	--architectures i386 \
	--bootappend-live "boot=live components hostname=tno-pki-m noeject nopersistance username=mikpont vga=775" \
	--linux-flavours 686-pae \
	--iso-application "TNO PKI Manager" \
	--iso-preparer "Serge Tensen sergetensen@protonmail.com" \
	--iso-publisher "Serge Tensen sergetensen@protonmail.com" \
	--iso-volume "TNO-PKI-M" \
	--memtest none \
	"${@}"
