#!/bin/sh

#	--debootstrap-options "--variant=minbase" \ This command generates a Kernel Panic.
#	--apt-indices false \
#	--apt-recommends false \


set -e

lb config noauto \
	--architectures i386 \
	--bootappend-live "boot=live consoleblank=0 components hostname=tno-pki-m noeject nopersistance username=mikpont \
	  vga=37" \
	--linux-flavours 686-pae \
	--iso-application "TNO PKI Manager" \
	--iso-preparer "Serge Tensen sergetensen@protonmail.com" \
	--iso-publisher "Serge Tensen sergetensen@protonmail.com" \
	--iso-volume "TNO-PKI-M" \
	--memtest none \
	"${@}"
